// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBuNu5Jav5nJ-laYtz9kEud5BOg2LGAU-g',
    appId: '1:901222599399:web:de4e8913735b530ab1b042',
    messagingSenderId: '901222599399',
    projectId: 'playzone-8d2b6',
    authDomain: 'playzone-8d2b6.firebaseapp.com',
    storageBucket: 'playzone-8d2b6.firebasestorage.app',
    measurementId: 'G-SCBK1BR6HQ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBsNNz4vt-t7LoMrLyKHLWmkdAi0ejcevs',
    appId: '1:901222599399:android:9c8c5d6d5f498c14b1b042',
    messagingSenderId: '901222599399',
    projectId: 'playzone-8d2b6',
    storageBucket: 'playzone-8d2b6.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAavvPqj0hfuyFPwDxJHhm0UNfhzPyTM_E',
    appId: '1:901222599399:ios:1046b32e0106bf05b1b042',
    messagingSenderId: '901222599399',
    projectId: 'playzone-8d2b6',
    storageBucket: 'playzone-8d2b6.firebasestorage.app',
    iosBundleId: 'com.osama.playzone',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAavvPqj0hfuyFPwDxJHhm0UNfhzPyTM_E',
    appId: '1:901222599399:ios:1046b32e0106bf05b1b042',
    messagingSenderId: '901222599399',
    projectId: 'playzone-8d2b6',
    storageBucket: 'playzone-8d2b6.firebasestorage.app',
    iosBundleId: 'com.osama.playzone',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBuNu5Jav5nJ-laYtz9kEud5BOg2LGAU-g',
    appId: '1:901222599399:web:db8fa26c3389c20db1b042',
    messagingSenderId: '901222599399',
    projectId: 'playzone-8d2b6',
    authDomain: 'playzone-8d2b6.firebaseapp.com',
    storageBucket: 'playzone-8d2b6.firebasestorage.app',
    measurementId: 'G-YG5YP7CXGQ',
  );
}
